title: "AI Book Blog"
author: "Alex Carter"
description: "Unlock the power of AI-driven book insights, expert reviews, and smart recommendations tailored for curious minds."
baseurl: ""
url: "https://thealexcarterai.github.io/my-ai-blog"
theme: minima

# SEO & Social Media
google_analytics: "G-NQS6Y3EH6D"
twitter_username: "thealexcarterai"
github_username: "thealexcarterai"
email: "thealexcarterai@gmail.com"

# Minima Customization
minima:
  skin: dark
  social_links:
    twitter: thealexcarterai
    github: thealexcarterai
    rss: true
  date_format: "%b %-d, %Y"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  style: compressed
