name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Trigger the workflow on push to 'main'
  pull_request:
    branches:
      - main  # Trigger the workflow on PR to 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Latest version of checkout action

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Use Ruby 3.1

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install  # Install dependencies from Gemfile

      - name: Build the Jekyll site
        run: |
          bundle exec jekyll build  # Builds the Jekyll site into the '_site' directory

      - name: List files after build
        run: ls -l _site  # Debugging step to confirm site files exist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # Standard way to deploy Jekyll sites
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub-provided token
          publish_dir: ./_site  # Deploy the built Jekyll site
